
var replaceIndexString = '#index#';

var dashboard_config_template = [
    '{',
    '  "rows": [',
    '    {',
    '      "title": "Graph",',
    '      "height": "400px",',
    '      "editable": false,',
    '      "collapse": false,',
    '      "collapsable": true,',
    '      "panels": [',
    '        {',
    '          "span": 10,',
    '          "editable": false,',
    '          "group": [',
    '            "default"',
    '          ],',
    '          "type": "histogram",',
    '          "mode": "count",',
    '          "time_field": "@timestamp",',
    '          "value_field": null,',
    '          "auto_int": true,',
    '          "resolution": 100,',
    '          "interval": "1h",',
    '          "fill": 3,',
    '          "linewidth": 3,',
    '          "timezone": "browser",',
    '          "spyable": true,',
    '          "zoomlinks": true,',
    '          "bars": true,',
    '          "stack": false,',
    '          "points": false,',
    '          "lines": false,',
    '          "legend": true,',
    '          "x-axis": true,',
    '          "y-axis": true,',
    '          "percentage": false,',
    '          "interactive": true,',
    '          "queries": {',
    '            "mode": "all",',
    '            "ids": [',
    '              0,',
    '              1',
    '            ]',
    '          },',
    '          "title": "Events over time",',
    '          "intervals": [',
    '            "auto",',
    '            "1s",',
    '            "1m",',
    '            "5m",',
    '            "10m",',
    '            "30m",',
    '            "1h",',
    '            "3h",',
    '            "12h",',
    '            "1d",',
    '            "1w",',
    '            "1M",',
    '            "1y"',
    '          ],',
    '          "options": true,',
    '          "tooltip": {',
    '            "value_type": "individual",',
    '            "query_as_alias": true',
    '          },',
    '          "scale": 1,',
    '          "y_format": "none",',
    '          "grid": {',
    '            "max": null,',
    '            "min": 0',
    '          },',
    '          "annotate": {',
    '            "enable": false,',
    '            "query": "*",',
    '            "size": 20,',
    '            "field": "priority",',
    '            "sort": [',
    '              "priority",',
    '              "desc"',
    '            ]',
    '          },',
    '          "pointradius": 5,',
    '          "show_query": true,',
    '          "legend_counts": true,',
    '          "zerofill": false,',
    '          "derivative": false,',
    '          "scaleSeconds": false',
    '        },',
    '        {',
    '          "error": false,',
    '          "span": 2,',
    '          "editable": false,',
    '          "type": "stats",',
    '          "loadingEditor": false,',
    '          "queries": {',
    '            "mode": "all",',
    '            "ids": [',
    '              0,',
    '              1',
    '            ]',
    '          },',
    '          "style": {',
    '            "font-size": "24pt"',
    '          },',
    '          "format": "number",',
    '          "mode": "count",',
    '          "display_breakdown": "yes",',
    '          "sort_field": "",',
    '          "sort_reverse": false,',
    '          "label_name": "Query",',
    '          "value_name": "Value",',
    '          "spyable": true,',
    '          "show": {',
    '            "count": true,',
    '            "min": false,',
    '            "max": false,',
    '            "mean": false,',
    '            "std_deviation": false,',
    '            "sum_of_squares": false,',
    '            "total": false,',
    '            "variance": false',
    '          },',
    '          "title": "Aggregates",',
    '          "field": "@timestamp"',
    '        },',
    '        {',
    '          "error": false,',
    '          "span": 4,',
    '          "editable": false,',
    '          "type": "terms",',
    '          "loadingEditor": false,',
    '          "field": "subject-id.raw",',
    '          "exclude": [],',
    '          "missing": false,',
    '          "other": true,',
    '          "size": 5,',
    '          "order": "count",',
    '          "style": {',
    '            "font-size": "10pt"',
    '          },',
    '          "donut": false,',
    '          "tilt": false,',
    '          "labels": true,',
    '          "arrangement": "horizontal",',
    '          "chart": "pie",',
    '          "counter_pos": "above",',
    '          "spyable": true,',
    '          "queries": {',
    '            "mode": "all",',
    '            "ids": [',
    '              0,',
    '              1',
    '            ]',
    '          },',
    '          "tmode": "terms",',
    '          "tstat": "total",',
    '          "valuefield": "",',
    '          "title": "Top 5 subjects"',
    '        },',
    '        {',
    '          "error": false,',
    '          "span": 4,',
    '          "editable": false,',
    '          "type": "terms",',
    '          "loadingEditor": false,',
    '          "field": "category.raw",',
    '          "exclude": [],',
    '          "missing": false,',
    '          "other": true,',
    '          "size": 5,',
    '          "order": "count",',
    '          "style": {',
    '            "font-size": "10pt"',
    '          },',
    '          "donut": false,',
    '          "tilt": false,',
    '          "labels": true,',
    '          "arrangement": "horizontal",',
    '          "chart": "pie",',
    '          "counter_pos": "above",',
    '          "spyable": true,',
    '          "queries": {',
    '            "mode": "all",',
    '            "ids": [',
    '              0,',
    '              1',
    '            ]',
    '          },',
    '          "tmode": "terms",',
    '          "tstat": "total",',
    '          "valuefield": "",',
    '          "title": "Top 5 categories"',
    '        },',
    '        {',
    '          "error": false,',
    '          "span": 4,',
    '          "editable": false,',
    '          "type": "terms",',
    '          "loadingEditor": false,',
    '          "field": "tresor-component.raw",',
    '          "exclude": [],',
    '          "missing": false,',
    '          "other": true,',
    '          "size": 5,',
    '          "order": "count",',
    '          "style": {',
    '            "font-size": "10pt"',
    '          },',
    '          "donut": false,',
    '          "tilt": false,',
    '          "labels": true,',
    '          "arrangement": "horizontal",',
    '          "chart": "pie",',
    '          "counter_pos": "above",',
    '          "spyable": true,',
    '          "queries": {',
    '            "mode": "all",',
    '            "ids": [',
    '              0,',
    '              1',
    '            ]',
    '          },',
    '          "tmode": "terms",',
    '          "tstat": "total",',
    '          "valuefield": "",',
    '          "title": "Top 5 tresor-components"',
    '        }',
    '      ],',
    '      "notice": false',
    '    },',
    '    {',
    '      "title": "Events",',
    '      "height": "350px",',
    '      "editable": false,',
    '      "collapse": false,',
    '      "collapsable": true,',
    '      "panels": [',
    '        {',
    '          "title": "All events",',
    '          "error": false,',
    '          "span": 12,',
    '          "editable": false,',
    '          "group": [',
    '            "default"',
    '          ],',
    '          "type": "table",',
    '          "size": 50,',
    '          "pages": 10,',
    '          "offset": 0,',
    '          "sort": [',
    '            "@timestamp",',
    '            "desc"',
    '          ],',
    '          "style": {',
    '            "font-size": "9pt"',
    '          },',
    '          "overflow": "min-height",',
    '          "fields": [',
    '            "@timestamp",',
    '            "priority",',
    '            "message",',
    '            "client-id",',
    '            "subject-id",',
    '            "category",',
    '            "tresor-component"',
    '          ],',
    '          "localTime": true,',
    '          "timeField": "@timestamp",',
    '          "highlight": [],',
    '          "sortable": true,',
    '          "header": true,',
    '          "paging": true,',
    '          "spyable": true,',
    '          "queries": {',
    '            "mode": "all",',
    '            "ids": [',
    '              0,',
    '              1',
    '            ]',
    '          },',
    '          "field_list": false,',
    '          "status": "Stable",',
    '          "trimFactor": 1000,',
    '          "normTimes": true,',
    '          "all_fields": false',
    '        }',
    '      ],',
    '      "notice": false',
    '    }',
    '  ],',
    '  "services": {',
    '    "query": {',
    '      "list": {',
    '        "0": {',
    '          "id": 0,',
    '          "type": "lucene",',
    '          "query": "*",',
    '          "alias": "",',
    '          "color": "#7EB26D",',
    '          "pin": false,',
    '          "enable": true',
    '        }',
    '      },',
    '      "ids": [',
    '        0',
    '      ]',
    '    },',
    '    "filter": {',
    '      "list": {',
    '        "0": {',
    '          "type": "time",',
    '          "field": "@timestamp",',
    '          "from": "now-1h",',
    '          "to": "now",',
    '          "mandate": "must",',
    '          "active": true,',
    '          "alias": "",',
    '          "id": 0',
    '        }',
    '      },',
    '      "ids": [',
    '        0',
    '      ]',
    '    }',
    '  },',
    '  "editable": false,',
    '  "style": "light",',
    '  "title": "TRESOR Logs",',
    '  "failover": false,',
    '  "index": {'+replaceIndexString+'},',
    '  "panel_hints": true,',
    '  "pulldowns": [',
    '    {',
    '      "type": "query",',
    '      "collapse": false,',
    '      "notice": false,',
    '      "enable": true,',
    '      "query": "*",',
    '      "pinned": true,',
    '      "history": [',
    '        "*"',
    '      ],',
    '      "remember": 10',
    '    },',
    '    {',
    '      "type": "filtering",',
    '      "collapse": false,',
    '      "notice": false,',
    '      "enable": true',
    '    }',
    '  ],',
    '  "nav": [',
    '    {',
    '      "type": "timepicker",',
    '      "collapse": false,',
    '      "notice": false,',
    '      "enable": true,',
    '      "status": "Stable",',
    '      "time_options": [',
    '        "5m",',
    '        "15m",',
    '        "30m",',
    '        "1h",',
    '        "6h",',
    '        "12h",',
    '        "24h",',
    '        "2d",',
    '        "7d",',
    '        "30d",',
    '        "90d",',
    '        "1y"',
    '      ],',
    '      "refresh_intervals": [',
    '        "5s",',
    '        "10s",',
    '        "30s",',
    '        "1m",',
    '        "5m",',
    '        "15m",',
    '        "30m",',
    '        "1h",',
    '        "2h",',
    '        "1d"',
    '      ],',
    '      "timefield": "@timestamp",',
    '      "now": true',
    '    }',
    '  ],',
    '  "loader": {',
    '    "save_gist": false,',
    '    "save_elasticsearch": false,',
    '    "save_local": false,',
    '    "save_default": false,',
    '    "save_temp": false,',
    '    "save_temp_ttl_enable": false,',
    '    "save_temp_ttl": "0s",',
    '    "load_gist": false,',
    '    "load_elasticsearch": false,',
    '    "load_elasticsearch_size": 0,',
    '    "load_local": false,',
    '    "hide": false,',
    '    "show_home": false',
    '  },',
    '  "refresh": false',
    '}',
    ''
].join("\n");

exports.getReplaceIndexString = function getReplaceIndexString() {
    return replaceIndexString;
}

exports.getDashboardConfigTemplate = function getDashboardConfigTemplate() {
    return dashboard_config_template;
}